---
title: "quiz8"
title-block-style: none
format: live-html
engine: knitr
sidebar:
  style: docked
resources:
  - crop_fertilizer_1.csv
  - crop_fertilizer_2.csv
---

{{< include /_extensions/r-wasm/live/_knitr.qmd >}}
{{< include /_extensions/r-wasm/live/_gradethis.qmd >}}

<script>
document.addEventListener("DOMContentLoaded", () => {
  const params = new URLSearchParams(window.location.search);
  const showQ = params.get("q");

  // Show only the requested section
  if (showQ) {
    document.querySelectorAll("section[id]").forEach(section => {
      if (section.id !== showQ) section.style.display = "none";
    });
  }

  // Hide page title
  document.querySelectorAll(".quarto-title-block")
    .forEach(el => el.style.display = "none");

  // Hide ALL section titles (## ...)
  document.querySelectorAll("section[id] > h2")
    .forEach(h => h.style.display = "none");
});
</script>

```{webr}
#| echo: false
#| output: false
options(digits = 8)
```

## Q1 — One-way ANOVA (extract key statistics) {#q1a}

Using the `crop_fertilizer_1.csv` dataset, fit a one-way ANOVA model using `aov()`.

From the ANOVA output, select one value each for:

- $\text{df}_1$ (numerator degrees of freedom)
- $\text{df}_2$ (denominator degrees of freedom)
- F-statistic

```{webr}
crop <- read.csv("crop_fertilizer_1.csv")

fit <- aov(___ ~ ___, data = ___)

summary(___)
```

```{webr}
# Solution
#| echo: false
#| output: false
crop <- read.csv("crop_fertilizer_1.csv")

fit <- aov(yield ~ fertilizer, data = crop)

summary(fit)

# df1 = 3
# df2 = 16
# F-statistic = 277.23
```

## Q1 — One-way ANOVA (extract key statistics) {#q1b}

Using the `crop_fertilizer_2.csv` dataset, fit a one-way ANOVA model using `aov()`.

From the ANOVA output, select one value each for:

- $\text{df}_1$ (numerator degrees of freedom)
- $\text{df}_2$ (denominator degrees of freedom)
- F-statistic

```{webr}
crop <- read.csv("crop_fertilizer_2.csv")

fit <- aov(___ ~ ___, data = ___)

summary(___)
```

```{webr}
# Solution
#| echo: false
#| output: false
crop <- read.csv("crop_fertilizer_2.csv")

fit <- aov(yield ~ fertilizer, data = crop)

summary(fit)

# df1 = 3
# df2 = 16
# F-statistic = 48.567 
```

## Q2 — One-way ANOVA (p-value and inference) {#q2a}

Using the `crop_fertilizer_1.csv` dataset, we test:

$H_0: \mu_A = \mu_B = \mu_C = \mu_D$

$H_a: \text{At least one population mean yield differs.}$

Compute the p-value using the `aov()` function.

Based on the ANOVA output, select all correct statements about the p-value and hypothesis test.

```{webr}
crop <- read.csv("crop_fertilizer_1.csv")

fit = aov(___ ~ ___, data = ___)

summary(___)
```

```{webr}
#| echo: false
#| output: false

crop <- read.csv("crop_fertilizer_1.csv")

fit = aov(yield ~ fertilizer, data = crop)

summary(fit)
# p-value = 5.332e-14
# We reject the null hypothesis at the 5% significance level.
```

## Q2 — One-way ANOVA (p-value and inference) {#q2b}

Using the `crop_fertilizer_2.csv` dataset, we test:

$H_0: \mu_A = \mu_B = \mu_C = \mu_D$

$H_a: \text{At least one population mean yield differs.}$

Compute the p-value using the `aov()` function.

Based on the ANOVA output, select all correct statements about the p-value and hypothesis test.
```{webr}
crop <- read.csv("crop_fertilizer_2.csv")

fit = aov(___ ~ ___, data = ___)

summary(___)
```

```{webr}
#| echo: false
#| output: false

crop <- read.csv("crop_fertilizer_2.csv")

fit = aov(yield ~ fertilizer, data = crop)

summary(fit)
# p-value = 2.93e-08
# We reject the null hypothesis at the 5% significance level.
```

## Q3 — Fisher's LSD {#q3a}

Using the `crop_fertilizer_1.csv` dataset, perform pairwise comparisons using the Fisher's LSD method.

Compute the p-value for the comparison between fertilizers **B** and **D**.

```{webr}
crop <- read.csv("crop_fertilizer_1.csv")

pairwise.t.test(___,____, p.adjust.method = ___)

```

```{webr}
#| echo: false
#| output: false
crop <- read.csv("crop_fertilizer_1.csv")

pairwise.t.test(crop$yield, crop$fertilizer, p.adjust.method = "none")

# 0.0112
```

## Q3 — Fisher's LSD {#q3b}

Using the `crop_fertilizer_2.csv` dataset, perform pairwise comparisons using the Fisher's LSD method.

Compute the p-value for the comparison between fertilizers **B** and **D**.

```{webr}
crop <- read.csv("crop_fertilizer_2.csv")

pairwise.t.test(____, ____, p.adjust.method = ____")
```

```{webr}
#| echo: false
#| output: false
crop <- read.csv("crop_fertilizer_2.csv")

pairwise.t.test(crop$yield, crop$fertilizer, p.adjust.method = "none")
# 0.0202
```

## Q4 — Fisher's LSD (number of significant pairs) {#q4a}

Using the `crop_fertilizer_1.csv` dataset, perform pairwise comparisons using Fisher's LSD method.

At the 5% significance level, how many pairs of fertilizers are significantly different?

```{webr}
crop <- read.csv("crop_fertilizer_1.csv")

pairwise.t.test(___, ___, p.adjust.method = ___)
```

```{webr}
#| echo: false
#| output: false
crop <- read.csv("crop_fertilizer_1.csv")

pairwise.t.test(crop$yield, crop$fertilizer, p.adjust.method = "none")
# 6  
```
## Q4 — Fisher's LSD (number of significant pairs) {#q4b}

Using the `crop_fertilizer_2.csv` dataset, perform pairwise comparisons using Fisher's LSD method.

At the 5% significance level, how many pairs of fertilizers are significantly different?

```{webr}
crop <- read.csv("crop_fertilizer_2.csv")

pairwise.t.test(___, ___, p.adjust.method = ___)
```

```{webr}
#| echo: false
#| output: false
crop <- read.csv("crop_fertilizer_2.csv")

pairwise.t.test(crop$yield, crop$fertilizer, p.adjust.method = "none")
# 6
```

## Q5 — Bonferroni Adjustment {#q5a}

Using the `crop_fertilizer_1.csv` dataset, perform pairwise comparisons using the Bonferroni method.

Compute the p-value for the comparison between fertilizers **B** and **D**.

```{webr}
crop <- read.csv("crop_fertilizer_1.csv")

pairwise.t.test(___, ___, p.adjust.method = ___)
```

```{webr}
#| echo: false
#| output: false
crop <- read.csv("crop_fertilizer_1.csv")

pairwise.t.test(crop$yield, crop$fertilizer, p.adjust.method = "bonferroni")
# 0.0670
```


## Q5 — Bonferroni Adjustment {#q5b}

Using the `crop_fertilizer_2.csv` dataset, perform pairwise comparisons using the Bonferroni method.

Compute the p-value for the comparison between fertilizers **B** and **D**.

```{webr}
crop <- read.csv("crop_fertilizer_2.csv")

pairwise.t.test(___, ___, p.adjust.method = ___)
```

```{webr}
#| echo: false
#| output: false
crop <- read.csv("crop_fertilizer_2.csv")

pairwise.t.test(crop$yield, crop$fertilizer, p.adjust.method = "bonferroni")
# 0.1212
```

## Q6 — Bonferroni Adjustment {#q6a}

Using the `crop_fertilizer_1.csv` dataset, perform pairwise comparisons using the Bonferroni method.

At the 5% significance level, how many pairs of fertilizers are significantly different?

```{webr}
crop <- read.csv("crop_fertilizer_1.csv")

pairwise.t.test(___, ___, p.adjust.method = ___)
```

```{webr}
#| echo: false
#| output: false
crop <- read.csv("crop_fertilizer_1.csv")

pairwise.t.test(crop$yield, crop$fertilizer, p.adjust.method = "bonferroni")
# 5
```


## Q6 — Bonferroni Adjustment {#q6b}

Using the `crop_fertilizer_2.csv` dataset, perform pairwise comparisons using the Bonferroni method.

At the 5% significance level, how many pairs of fertilizers are significantly different?

```{webr}
crop <- read.csv("crop_fertilizer_2.csv")

pairwise.t.test(___, ___, p.adjust.method = ___)
```

```{webr}
#| echo: false
#| output: false
crop <- read.csv("crop_fertilizer_2.csv")

pairwise.t.test(crop$yield, crop$fertilizer, p.adjust.method = "bonferroni")
# 4
```


