---
title: "Quiz 1a"
format: live-html
engine: knitr
sidebar:
  style: docked
resources:
  - height_weight.csv
  - visits.csv
---

{{< include /_extensions/r-wasm/live/_knitr.qmd >}}
{{< include /_extensions/r-wasm/live/_gradethis.qmd >}}
## Q1 — Create a vector {#q1}

Make a vector called `my_vec` that contains the numbers updates **-10, 24, -45, 12**.

```{webr}
my_vec <- NULL
my_vec
```

::: {.callout-tip collapse="true" title="Solution"}
```{webr}
my_vec <- c(-10, 24, -45, 12)
my_vec
```
:::


## Q2 — Find the average {#q2}

Compute the mean of the vector `c(1,7,9,16,32)`.\
Your answer should be stored in a variable called `avg_val`.

```{webr}
avg_val <- NULL
avg_val
```

::: {.callout-tip collapse="true" title="Solution"}
```{webr}
avg_val <- mean(c(1,7,9,16,32))
avg_val
```
:::

## Q3 — Draw a histogram from Height-Weight dataset {#q3}
```{webr}
#| echo: false
my_data <- read.csv('height_weight.csv')
```

::: {.callout-note title="Preview"}
Find a preview of the Height-Weight dataset here:
```{webr}
#| echo: true
head(my_data, 8)
```
:::

Draw a histogram from `my_data` dataset using the `height` column:
```{webr}
#| echo: true
```

::: {.callout-tip collapse="true" title="Solution"}
```{webr}
hist(my_data$height)
```
:::

## Q4 — Draw a boxplot from Height-Weight dataset {#q4}

::: {.callout-note title="Preview"}
Find a preview of the Height-Weight dataset here:
```{webr}
#| echo: true
head(my_data, 8)
```
:::
Draw a boxplot from `my_data` dataset using the `height` column:
```{webr}

```

::: {.callout-tip collapse="true" title="Solution"}
```{webr}
boxplot(my_data$height)
```
:::

## Q5 — Load a CSV as a DataFrame {#q5}

Load 'visits.csv' into a dataframe named df.

```{webr}
df <- NULL
head(df)
```

::: {.callout-tip collapse="true" title="Solution"}
```{webr}
df <- read.csv("visits.csv")
head(df)
```
:::


## Q6 — Count rows in 'df' {#q6}

Count the number of rows in 'df' and store them in the variable 'rows'

```{webr}
rows <- NULL
rows
```

::: {.callout-tip collapse="true" title="Solution"}
```{webr}
rows <- nrow(df)
rows
```
:::

## Q7 — Show column names {#q7}

Print the column names from 'df'

```{webr}
# Read the CSV and print the column names
cols <- NULL
cols
```

::: {.callout-tip collapse="true" title="Solution"}
```{webr}
cols <- names(df)
cols
```
:::
## Q8 — Calculate the mean number of visits per day {#q8}

Determine the average number of visits per day.
```{webr}
avg_visit <- NULL
avg_visit
```

::: {.callout-tip collapse="true" title="Solution"}
```{webr}
avg_visit <- mean(df$Visits)
avg_visit
```
:::

## Q9 — Calculate the sample variance of number of visits per day {#q9}

Determine the sample variance of the number of visits per day.
```{webr}
sample_variance_visits <- NULL
sample_variance_visits
```

::: {.callout-tip collapse="true" title="Solution"}
```{webr}
sample_variance_visits <- var(df$Visits)
sample_variance_visits
```
:::

## Q10 — Calculate the maximum number of visits per day {#q10}

Determine the maximum number of visits per day
```{webr}
maximum_visits <- NULL
maximum_visits
```

::: {.callout-tip collapse="true" title="Solution"}
```{webr}
maximum_visits <- max(df$Visits)
maximum_visits
```
:::
