---
title: "Quiz 1b"
format: live-html
engine: knitr
sidebar:
  style: docked
resources:
  - height_weight2.csv
  - sales.csv
---

{{< include /_extensions/r-wasm/live/_knitr.qmd >}}
{{< include /_extensions/r-wasm/live/_gradethis.qmd >}}

<script>
document.addEventListener("DOMContentLoaded", () => {
  const params = new URLSearchParams(window.location.search);
  const showQ = params.get("q");

  // Show only the requested section
  if (showQ) {
    document.querySelectorAll("section[id]").forEach(section => {
      if (section.id !== showQ) section.style.display = "none";
    });
  }

  // Hide page title
  document.querySelectorAll(".quarto-title-block")
    .forEach(el => el.style.display = "none");

  // Hide ALL section titles (## ...)
  document.querySelectorAll("section[id] > h2")
    .forEach(h => h.style.display = "none");
});
</script>


## Q1 — Getting an Element of a Vector by Index {#q1}

What is the element at index 100 of `my_vec`?

```{webr}
#| echo: false
set.seed(1)
my_vec <- rnorm(1000, mean = 100, sd = 10)
```

```{webr}

```

```{webr}
#| echo: false
#| output: false
my_vec[100]
#95.2660
```
## Q2 — Find the Sample Variance {#q2}

Compute the sample variance of c(5,10,12,15,19).

```{webr}

```

```{webr}
#| echo: false
#| output: false
var(c(5,10,12,15,19))
#27.7
```
## Q3 — Draw a Histogram {#q3}
The `height_weight2.csv` dataset contains measurements of individuals' heights (cm) and weights (kgs). 

Draw a histogram of the `weight` column from `height_weight2.csv` to answer the following question:
Based on the histogram, which statement best describes the distribution of weights?
```{webr}

```

```{webr}
#| echo: false
#| output: false
hw = read.csv("height_weight2.csv")
hist(hw$weight)
# Approximately symmetric and bell-shaped
```
## Q4 — Draw a Boxplot {#q4}
The `height_weight2.csv` dataset contains measurements of individuals' heights (cm) and weights (kgs). 

Draw a boxplot of the `weight` column from `height_weight2.csv` to answer the following question.

What is the median `weight` in the dataset? *(Answers within ±3 will be considered correct.)*
```{webr}

```

```{webr}
#| echo: false
#| output: false
hw = read.csv("height_weight2.csv")
boxplot(hw$weight)
#71.15 ±3
```
## Q5 — Outliers Existence {#q5}
The `height_weight2.csv` dataset contains measurements of individuals' heights (cm) and weights (kgs). 

Draw a boxplot of the `weight` column from `height_weight2.csv` to answer the following question.

Does the boxplot suggest the presence of any outliers?
```{webr}

```

```{webr}
#| echo: false
#| output: false
hw = read.csv("height_weight2.csv")
boxplot(hw$weight)
# No outliers
```
## Q6 — Count rows {#q6}
The `sales.csv` dataset consists of the number of units sold for each day. 

How many rows are in `sales.csv`?
```{webr}

```

```{webr}
#| echo: false
#| output: false
df_sales = read.csv("sales.csv")
nrow(df_sales)
#20
```
## Q7 — Count Columns {#q7}
The `sales.csv` dataset consists of the number of units sold for each day. 

How many columns are in `sales.csv`?
```{webr}


```

```{webr}
#| echo: false
#| output: false

```
## Q8 — Standard Deviation of Units Sold {#q8}
The `sales.csv` dataset consists of the number of units sold for each day. 

What is the sample standard deviation of the `units_sold` column in `sales.csv`?
```{webr}

```

```{webr}
#| echo: false
#| output: false
df_sales = read.csv("sales.csv")
ncol(df_sales)
#2
```
## Q9 — Sum of Sales {#q9}
The `sales.csv` dataset consists of the number of units sold for each day. 

What is the sum of the `units_sold` column in `sales.csv`?
```{webr}

```

```{webr}
#| echo: false
#| output: false
df_sales = read.csv("sales.csv")
sum(df_sales$units_sold)
#303
```
## Q10 — Minimum Sales {#q10}
The `sales.csv` dataset consists of the number of units sold for each day. 

What is the minimum number of sales in a single day in `sales.csv`?
```{webr}

```

```{webr}
#| echo: false
#| output: false
df_sales = read.csv("sales.csv")
min(df_sales$units_sold)
#8
```