---
title: "SAMPLE_QUIZ"
title-block-style: none
format: live-html
engine: knitr
sidebar:
  style: docked
resources:
  -  ads_A.csv
  -  ads_B.csv
---

{{< include /_extensions/r-wasm/live/_knitr.qmd >}}
{{< include /_extensions/r-wasm/live/_gradethis.qmd >}}

<script>
document.addEventListener("DOMContentLoaded", () => {
  const params = new URLSearchParams(window.location.search);
  const showQ = params.get("q");

  // Show only the requested section
  if (showQ) {
    document.querySelectorAll("section[id]").forEach(section => {
      if (section.id !== showQ) section.style.display = "none";
    });
  }

  // Hide page title
  document.querySelectorAll(".quarto-title-block")
    .forEach(el => el.style.display = "none");

  // Hide ALL section titles (## ...)
  document.querySelectorAll("section[id] > h2")
    .forEach(h => h.style.display = "none");
});
</script>

## Q1 — Visualize the Relationship {#q1a}
Using the `ads_A.csv` dataset:

Does the plot suggest a linear relationship?
```{webr}
quiz <- read.csv("ads_A.csv") 
plot(quiz$ad_spend, quiz$views,
     xlab = "Ad Spend ($)", ylab = "Views")
abline(lm(views ~ ad_spend, data = quiz), col = "blue")
```

```{webr}
#| echo: false
#| output: false

# Yes
```

## Q1 — Visualize the Relationship {#q1b}
Using the `ads_B.csv` dataset:

Does the plot suggest a linear relationship?
```{webr}
quiz <- read.csv("ads_B.csv") 
plot(quiz$ad_spend, quiz$views,
     xlab = "Ad Spend ($)", ylab = "Views")
abline(lm(views ~ ad_spend, data = quiz), col = "blue")
```

```{webr}
#| echo: false
#| output: false

# Yes
```

## Q2 - Numerical Answer {#q2a}
Using the `ads_A.csv` dataset:

Conduct a two-sided one-sample t-test to determine whether the true mean number of views is significantly different from 20,000. Use a significance level of 0.05.

```{webr}
df <- read.csv("ads_A.csv")
x <- df$views

mu_0 <- ___
n <- ___
xbar <- ___
s <- ___

t_stat <- ___
t_stat
```

```{webr}
#| echo: false
#| output: false
df <- read.csv("ads_A.csv")
x <- df$views

mu_0 <- 20000
n <- length(x)
xbar <- mean(x)
s <- sd(x)

t_stat <- (xbar - mu_0) / (s / sqrt(n))
t_stat
# 
```



## Q2 - Numerical Answer {#q2b}
Using the `ads_B.csv` dataset:

Conduct a two-sided one-sample t-test to determine whether the true mean number of views is significantly different from 30,000. Use a significance level of 0.05.

```{webr}
df <- read.csv("ads_B.csv")
x <- df$views

mu_0 <- ___
n <- ___
xbar <- ___
s <- ___

t_stat <- ___
t_stat
```

```{webr}
#| echo: false
#| output: false
df <- read.csv("ads_B.csv")
x <- df$views

mu_0 <- 30000
n <- length(x)
xbar <- mean(x)
s <- sd(x)

t_stat <- (xbar - mu_0) / (s / sqrt(n))
t_stat
# 
```