---
title: "quiz9"
title-block-style: none
format: live-html
engine: knitr
sidebar:
  style: docked
resources:
    - health_metrics.csv
---

{{< include /_extensions/r-wasm/live/_knitr.qmd >}}
{{< include /_extensions/r-wasm/live/_gradethis.qmd >}}

<script>
document.addEventListener("DOMContentLoaded", () => {
  const params = new URLSearchParams(window.location.search);
  const showQ = params.get("q");

  // Show only the requested section
  if (showQ) {
    document.querySelectorAll("section[id]").forEach(section => {
      if (section.id !== showQ) section.style.display = "none";
    });
  }

  // Hide page title
  document.querySelectorAll(".quarto-title-block")
    .forEach(el => el.style.display = "none");

  // Hide ALL section titles (## ...)
  document.querySelectorAll("section[id] > h2")
    .forEach(h => h.style.display = "none");
});
</script>

## Q1 — Linear trend {#q1a}
Using the dataset `health_metrics.csv`, plot `sbp` vs `sodium` to determine whether there exists a linear trend. 

```{webr}
df <- read.csv("health_metrics.csv")

```

```{webr}
#| echo: false
#| output: false
df <- read.csv("health_metrics.csv")
plot(df$sodium, df$sbp)

# yes there's a linear trend
```

## Q1 — Linear trend {#q1b}
Using the dataset `health_metrics.csv`, plot `sbp` vs `hr` to determine whether there exists a linear trend. 

```{webr}
df <- read.csv("health_metrics.csv")

```

```{webr}
#| echo: false
#| output: false
df <- read.csv("health_metrics.csv")
plot(df$hr, df$sbp)

# no linear trend
```

## Q2 — One feature {#q2a}
Using the dataset `health_metrics.csv`, fit a linear regression model to predict systolic blood pressure, `sbp` using `age` as the only predictor. 

Compute the estimated intercept $\beta_{0}$.

```{webr}
df <- read.csv("health_metrics.csv")

```

```{webr}
#| echo: false
#| output: false
df <- read.csv("health_metrics.csv")
model <- lm(sbp ~ age, data = df)
coef(model)
# 64.295328
```

## Q2 — One feature {#q2b}
Using the dataset `health_metrics.csv`, fit a linear regression model to predict systolic blood pressure,`sbp` using `sodium` as the only predictor. 

Compute the estimated slope $\beta_{1}$.

```{webr}
df <- read.csv("health_metrics.csv")

```

```{webr}
#| echo: false
#| output: false
df <- read.csv("health_metrics.csv")
model <- lm(sbp ~ sodium, data = df)
coef(model)
# 0.04144923 
```

## Q3 — Predict {#q3a}
Using the dataset `health_metrics.csv`, predict the systolic blood pressure for when $\text{sodium} = 2000$. 

Hint: use `predict` or use $\beta_{0}$ and $\beta_{1}$ to calculate it by hand.
```{webr}
df <- read.csv("health_metrics.csv")

```

```{webr}
#| echo: false
#| output: false
df <- read.csv("health_metrics.csv")
model <- lm(sbp ~ sodium, data = df)
predict(model, newdata = data.frame(sodium=2000))
# 115.2822 
```

## Q3 — Predict {#q3b}
Using the dataset `health_metrics.csv`, predict the diabetes progression for when $\text{bmi} = 23$. 

Hint: use `predict` or use $\beta_{0}$ and $\beta_{1}$ to calculate it by hand.
```{webr}
df <- read.csv("health_metrics.csv")

```

```{webr}
#| echo: false
#| output: false
df <- read.csv("health_metrics.csv")
model <- lm(sbp ~ bmi, data = df)
predict(model, newdata = data.frame(bmi = 23))
# 113.9065
```

## Q4 - Interpret Intercept {#q4a}
Suppose we have the regression equation $\hat{y} = 2x+5$, where $x$ represents the number of days and $y$ represents plant height. 
What does the intercept represent? This model is hypothetical and unrelated to the `health_metrics.csv` dataset. 

## Q4 - Interpret Intercept {#q4b}
Suppose we have the regression equation $\hat{y} = 4x-10$, where $x$ represents the number of weeks of training and $y$ represents fitness score. 
What does the intercept represent? This model is hypothetical and unrelated to the `health_metrics.csv` dataset. 

## Q5 - Interpret Slope {#q5a}
Suppose we have the regression equation $\hat{y} = 3x+40$, where $x$ represents hours studied and $y$ represents the exam score. 
What does the slope represent? This model is hypothetical and unrelated to the `health_metrics.csv` dataset. 

## Q5 - Interpret Slope {#q5b}
Suppose we have the regression equation $\hat{y} = 80-2x$, where $x$ represents hours of screen time and $y$ represents sleep quality. 
What does the slope represent?This model is hypothetical and unrelated to the `health_metrics.csv` dataset. 

## Q6 - Residual {#q6a}
Using the dataset `health_metrics.csv`, fit a linear regression model predicting `sbp` from `bmi`. 
For the third observation in the dataset, calculate the residual.
Hint: recall the formula for residual, `residual = actual − predicted`
```{webr}
df <- read.csv("health_metrics.csv")

```

```{webr}
#| echo: false
#| output: false
df <- read.csv("health_metrics.csv")
model <- lm(sbp ~ bmi, data = df)
actual <- df$sbp[3]
pred <- predict(model, newdata = df[3, ])
actual - pred

# 2.077986
```

## Q6 - Residual {#q6b}
Using the dataset `health_metrics.csv`, fit a linear regression model predicting `sbp` from `sodium`. 
For the fourth observation in the dataset, calculate the residual.
Hint: recall the formula for residual, `residual = actual − predicted`
```{webr}
df <- read.csv("health_metrics.csv")

```

```{webr}
#| echo: false
#| output: false
df <- read.csv("health_metrics.csv")
model <- lm(sbp ~ sodium, data = df)
actual <- df$sbp[4]
pred <- predict(model, newdata = df[4, ])
actual - pred

# -1.369122
```

## Q7 - Residual Meaning {#q7a}
Using the dataset `health_metrics.csv`, a regression model is used to predict systolic blood pressure (`sbp`) from sodium intake. Suppose that for a particular patient, the residual is +8. Interpret the meaning of this residual.

## Q7 - Interpret Slope {#q7b}
Using the dataset `health_metrics.csv`, a regression model is used to predict systolic blood pressure (`sbp`) from sodium intake. Suppose that for a particular patient, the residual is -7. Interpret the meaning of this residual.